FROM jj/nginx
MAINTAINER Justin<justin@5nas.cc>

#COPY rpm rpm
RUN rpm -ivh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
 
RUN rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
RUN  yum -y install php70w.x86_64 php70w-cli.x86_64 php70w-common.x86_64 php70w-gd.x86_64 php70w-ldap.x86_64 php70w-mbstring.x86_64 php70w-mcrypt.x86_64 php70w-mysql.x86_64 php70w-pdo.x86_64 \
    yum -y install php70w-fpm \
    && rm -rf /var/cache/yum/*
RUN rm -rf rpm

#CMD ["php", "-a"]




